inventory/inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tracker.urls')),
    path('admin/', admin.site.urls),
]

inventory/tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('edit_inventory_item/<int:inventory_item_id>', views.edit_inventory_item, name='edit_inventory_item'),
    path('create_inventory_item/', views.create_inventory_item, name='create_inventory_item'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('delete_inventory_item/<int:inventory_item_id>', views.delete_inventory_item, name='delete_inventory_item'),
    path('export_inventory_to_csv/', views.export_inventory_to_csv, name='export_inventory_to_csv'),
]

inventory/tracker/models.py
from django.db import models

# Create your models here.
class InventoryItem(models.Model):
    item_name = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    item_description = models.CharField(max_length=500)
    stock_quantity = models.IntegerField(default=0)
    item_location = models.CharField(max_length=50)
    release_date = models.DateTimeField('release date')

    def __str__(self):
        return self.company + ": " + self.item_name

inventory/tracker/views.py
import csv

from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import InventoryItem


class IndexView(generic.ListView):
    template_name = 'tracker/index.html'
    context_object_name = 'inventory_item_list'

    def get_queryset(self):
        return InventoryItem.objects.all()

class DetailView(generic.DetailView):
    model = InventoryItem
    template_name = 'tracker/detail.html'

def create(request):
    return render(request, 'tracker/create.html')

class EditView(generic.DetailView):
    model = InventoryItem
    template_name = 'tracker/edit.html'

class DeleteView(generic.DetailView):
    model = InventoryItem
    template_name = 'tracker/delete.html'

def edit_inventory_item(request, inventory_item_id):
    inventory_item = get_object_or_404(InventoryItem, pk=inventory_item_id)
    update_item_name = request.POST['item_name']
    update_company = request.POST['company']
    update_item_description = request.POST['item_description']
    update_stock_quantity = request.POST['stock_quantity']
    update_item_location = request.POST['item_location']
    update_release_date = request.POST['release_date']

    inventory_item.item_name = update_item_name
    inventory_item.company = update_company
    inventory_item.item_description = update_item_description
    inventory_item.stock_quantity = update_stock_quantity
    inventory_item.item_location = update_item_location
    inventory_item.release_date = update_release_date

    inventory_item.save()

    return HttpResponseRedirect(reverse('tracker:detail', args=(inventory_item.id,)))

def create_inventory_item(request):
    create_item_name = request.POST['item_name']
    create_company = request.POST['company']
    create_item_description = request.POST['item_description']
    create_stock_quantity = request.POST['stock_quantity']
    create_item_location = request.POST['item_location']
    create_release_date = request.POST['release_date']

    new_inventory_item = InventoryItem(
        item_name = create_item_name,
        company = create_company,
        item_description = create_item_description,
        stock_quantity = create_stock_quantity,
        item_location = create_item_location,
        release_date = create_release_date
    )
    new_inventory_item.save()

    return HttpResponseRedirect(reverse('tracker:detail', args=(new_inventory_item.id,)))


def delete_inventory_item(request, inventory_item_id):
    inventory_item = get_object_or_404(InventoryItem, pk=inventory_item_id)
    inventory_item.delete()

    return HttpResponseRedirect(reverse('tracker:index'))



def export_inventory_to_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="inventory.csv"'

    writer = csv.writer(response)
    writer.writerow(['item_name', 'company', 'item_description', 'stock_quantity', 'item_location', 'release_date'])

    inventory = InventoryItem.objects.all().values_list('item_name', 'company', 'item_description', 'stock_quantity', 'item_location', 'release_date')

    for item in inventory:
        writer.writerow(item)

    return  response

inventory/tracker/templates/tracker/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create New Inventory Item</title>
</head>
<body>
<h1>Create Inventory Item</h1>
<form action="{% url 'tracker:create_inventory_item' %}" method="post">
{% csrf_token %}
    <label for="item_name">Item Name: </label>
    <input type="text" name="item_name" id="item_name" required>

    <label for="company">Company: </label>
    <input type="text" name="company" id="company" required>

    <label for="item_description">Item Description: </label>
    <textarea type="item_description" name="item_description" id="item_description" rows="10" cols="50"> </textarea>

    <label for="stock_quantity">Stock Quantity: </label>
    <input type="number" name="stock_quantity" id="stock_quantity">

    <label for="item_location">Item Location: </label>
    <input type="text" name="item_location" id="item_location">

    <label for="release_date">release_date: </label>
    <input type="date" name="release_date" id="release_date">

    <input type="submit" id="submit" value="Submit">
</form>

<div>
      <a href="{% url 'tracker:index' %}"> Back to List of Contacts </a>
</div>

</body>
</html>

inventory/tracker/templates/tracker/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Inventory Item</title>
</head>
<body>
<h1>Delete Inventory Item</h1>
<form action="{% url 'tracker:delete_inventory_item' inventoryitem.id %}" method="post">
{% csrf_token %}
    <label for="item_name">Item Name: </label>
    <input type="text" name="item_name" id="item_name" value="{{ inventoryitem.item_name}}" readonly>

    <label for="company">Company: </label>
    <input type="text" name="company" id="company" value="{{ inventoryitem.company}}" readonly>

    <label for="item_description">Item Description: </label>
    <textarea type="item_description" name="item_description" id="item_description" rows="10" cols="50" readonly>{{inventoryitem.item_description}}</textarea>

    <label for="stock_quantity">Stock Quantity: </label>
    <input type="number" name="stock_quantity" id="stock_quantity" value="{{ inventoryitem.stock_quantity}}" readonly>

    <label for="item_location">Item Location: </label>
    <input type="text" name="item_location" id="item_location" value="{{ inventoryitem.item_location}}" readonly>

    <label for="release_date">release_date: </label>
    <input type="date" name="release_date" id="release_date" value="{{inventoryitem.release_date | date:"Y-m-d"}}" readonly>

    <input type="submit" id="submit" value="Delete">
</form>

<div>
     <a href="{% url 'tracker:detail' inventoryitem.id %}"> Back to Details </a>
</div>

</body>
</html>

inventory/tracker/templates/tracker/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>Inventory Item: {{ inventoryitem.item_name }} {{ inventoryitem.company }}</h1>
<ul>
    <li>
        Item name: {{ inventoryitem.item_name }}
    </li>
    <li>
        Company: {{ inventoryitem.company }}
    </li>
    <li>
        Item Description: {{ inventoryitem.item_description }}
    </li>
    <li>
        Stock Quantity: {{ inventoryitem.stock_quantity }}
    </li>
    <li>
        Item Location: {{ inventoryitem.item_location }}
    </li>
    <li>
        Release Date: {{ inventoryitem.release_date }}
    </li>
</ul>
<div>
     <a href="{% url 'tracker:index' %}"> List of Inventory Items </a>
    |
     <a href="{% url 'tracker:edit' inventoryitem.id %}"> Edit Inventory Item </a>
    |
     <a href="{% url 'tracker:delete' inventoryitem.id %}"> Delete Inventory Item </a>
</div>

</body>
</html>

inventory/tracker/templates/tracker/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Inventory Item</title>
</head>
<body>
<h1>Edit Inventory Item</h1>
<form action="{% url 'tracker:edit_inventory_item' inventoryitem.id %}" method="post">
{% csrf_token %}
    <label for="item_name">Item Name: </label>
    <input type="text" name="item_name" id="item_name" value="{{ inventoryitem.item_name}}" required>

    <label for="company">Company: </label>
    <input type="text" name="company" id="company" value="{{ inventoryitem.company}}" required>

    <label for="item_description">Item Description: </label>
    <textarea type="item_description" name="item_description" id="item_description" rows="10" cols="50">{{inventoryitem.item_description}}</textarea>

    <label for="stock_quantity">Stock Quantity: </label>
    <input type="number" name="stock_quantity" id="stock_quantity" value="{{ inventoryitem.stock_quantity}}">

    <label for="item_location">Item Location: </label>
    <input type="text" name="item_location" id="item_location" value="{{ inventoryitem.item_location}}">

    <label for="release_date">release_date: </label>
    <input type="date" name="release_date" id="release_date" value="{{inventoryitem.release_date | date:"Y-m-d"}}">

    <input type="submit" id="submit" value="Submit">
</form>

<div>
     <a href="{% url 'tracker:detail' inventoryitem.id %}"> Back to Details </a>
</div>

</body>
</html>

inventory/tracker/templates/tracker/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventory Tracker</title>
</head>
<body>
<h1>Inventory Tracker</h1>
{% if inventory_item_list %}
    <ul>
    {% for item in inventory_item_list %}
        <li><a href="{% url 'tracker:detail' item.id %}">{{ item.item_name }} {{ item.company }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Items in inventory</p>
{% endif %}
<a href="{% url 'tracker:create' %}"> Create New Inventory Item</a>
|
<a href="{% url 'tracker:export_inventory_to_csv' %}"> Export Inventory to CSV</a>
</body>
</html>